
FROM node:12-alpine AS test-dev

ENV STATIC_HOST=localhost
ENV STATIC_PORT=3000
ENV SOCKET_HOST=localhost
ENV SOCKET_PORT=4000

WORKDIR /mafioso/tests

COPY package.json package-lock.json ./
ENV NODE_ENV=development 
RUN npm install 

COPY . .

CMD ["npm", "run", "smoke"]
