
FROM node:12-alpine AS test-prod

ENV STATIC_HOST=195.133.1.11
ENV STATIC_PORT=3000
ENV SOCKET_HOST=195.133.1.11
ENV SOCKET_PORT=4000

WORKDIR /mafioso/tests

COPY package.json package-lock.json ./
ENV NODE_ENV=development 
RUN npm install 

COPY . .

CMD ["npm", "run", "smoke"]
